import './style.css';

type P={name:string,s:number[]}; type Side=0|1;
const C=document.querySelector<HTMLCanvasElement>('#game')!,X=C.getContext('2d')!;
const raw=['787765SELES','989520VENUS','567420DOKICI','687789CHRIS','346430ANNA','768524CLIJSTER','979746GRAF','887657SABATINI','465999SANCHEZ','364735DATEKIMI','878620DAVENPO','677999NAVRATIL','786879HINGIS','467338PIERCE','567350SHARAPO','466698NOVOTNA'];
const ps:P[]=raw.map(v=>({name:v.slice(6),s:[...v.slice(0,6)].map(Number)}));
const keys=new Set<string>(), pressed=new Set<string>();
addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space','Enter','Escape'].includes(e.code))e.preventDefault();if(!keys.has(e.code))pressed.add(e.code);keys.add(e.code)});
addEventListener('keyup',e=>keys.delete(e.code)); addEventListener('blur',()=>keys.clear());
const take=(k:string)=>{const v=pressed.has(k);pressed.delete(k);return v},cl=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const txt=(s:string,x:number,y:number,n=18,a:CanvasTextAlign='center')=>{X.font=`700 ${n}px ui-monospace,monospace`;X.textAlign=a;X.textBaseline='middle';X.fillText(s,x,y)};
const panel=(x:number,y:number,w:number,h:number)=>{X.fillStyle='rgba(10,20,15,.88)';X.fillRect(x,y,w,h);X.strokeStyle='#586c5d';X.strokeRect(x+.5,y+.5,w-1,h-1)};
function proj(x:number,y:number,z=0){const t=cl((y+178)/356,0,1),s=.66+t*.52;return{x:300+x*s*1.78,y:94+t*428-z*s*1.72,s}}
function court(){X.fillStyle='#526446';X.fillRect(0,0,600,600);X.fillStyle='#657b57';const a=proj(-82,-178),b=proj(82,-178),c=proj(82,178),d=proj(-82,178);X.beginPath();X.moveTo(a.x,a.y);X.lineTo(b.x,b.y);X.lineTo(c.x,c.y);X.lineTo(d.x,d.y);X.fill();X.strokeStyle='#eef0dc';X.lineWidth=2;const ln=(x1:number,y1:number,x2:number,y2:number)=>{const p=proj(x1,y1),q=proj(x2,y2);X.beginPath();X.moveTo(p.x,p.y);X.lineTo(q.x,q.y);X.stroke()};ln(-82,-178,-82,178);ln(82,-178,82,178);ln(-82,-178,82,-178);ln(-82,178,82,178);ln(-82,-100,82,-100);ln(-82,100,82,100);ln(0,-100,0,100);const n1=proj(-90,0,18),n2=proj(90,0,18),g1=proj(-90,0),g2=proj(90,0);X.fillStyle='rgba(240,240,225,.7)';X.beginPath();X.moveTo(n1.x,n1.y);X.lineTo(n2.x,n2.y);X.lineTo(g2.x,g2.y);X.lineTo(g1.x,g1.y);X.fill()}
class Actor{x=0;y:number;sw=0;hit=false;constructor(public side:Side,public p:P){this.y=side? -132:132} speed(){return 92+this.p.s[3]!*8.5} move(dx:number,dy:number,dt:number){const l=Math.hypot(dx,dy)||1;this.x=cl(this.x+dx/l*this.speed()*dt,-102,102);this.y=this.side?cl(this.y+dy/l*this.speed()*dt,-194,-12):cl(this.y+dy/l*this.speed()*dt,12,194)} swing(){if(this.sw)return;this.sw=.34;this.hit=false} update(dt:number){this.sw=Math.max(0,this.sw-dt)} draw(){const p=proj(this.x,this.y),f=this.side?1:-1,t=this.sw?1-this.sw/.34:0,k=this.sw?Math.sin(t*Math.PI):0;X.save();X.translate(p.x,p.y);X.scale(p.s,p.s);X.fillStyle='rgba(0,0,0,.25)';X.beginPath();X.ellipse(0,5,10,4,0,0,7);X.fill();X.strokeStyle=this.side?'#233249':'#eff1d5';X.fillStyle=this.side?'#dbe2eb':'#eee4b8';X.lineWidth=3;X.beginPath();X.arc(0,-17,4,0,7);X.fill();X.beginPath();X.moveTo(0,-12);X.lineTo(0,1);X.moveTo(0,-3);X.lineTo(-6,8);X.moveTo(0,-3);X.lineTo(6,8);X.stroke();const ax=7+k*7*f,ay=-9+k*4;X.beginPath();X.moveTo(0,-9);X.lineTo(ax,ay);X.stroke();X.strokeStyle='#8d6137';X.lineWidth=2;X.beginPath();X.moveTo(ax,ay);X.lineTo(ax+8*f,ay-8+k*8);X.stroke();X.beginPath();X.ellipse(ax+11*f,ay-11+k*8,4,7,.35*f,0,7);X.stroke();X.restore()}}
class Match{a:[Actor,Actor];ball={x:0,y:0,z:0,vx:0,vy:0,vz:0};pts:[number,number]=[0,0];games:[number,number]=[0,0];server:Side=0;last:Side=0;bounces=0;toss=false;live=false;serveLive=false;delay=.8;msg='GET READY';done:Side|null=null;pointNo=0;attempt=1;
constructor(u:P,cpu:P){this.a=[new Actor(0,u),new Actor(1,cpu)];this.reset()}
reset(){const s=this.a[this.server],r=this.a[this.server?0:1],right=this.pointNo%2===0;s.x=right?34:-34;s.y=this.server?-152:152;r.x=0;r.y=this.server?132:-132;this.ball={x:s.x+(this.server?-5:5),y:s.y,z:12,vx:0,vy:0,vz:0};this.toss=this.live=this.serveLive=false;this.bounces=0;this.attempt=1;this.delay=.65;this.msg=this.server?'CPU SERVES':'YOUR SERVE'}
launch(tx:number,ty:number,t:number,arc=.95){this.ball.vx=(tx-this.ball.x)/t;this.ball.vy=(ty-this.ball.y)/t;this.ball.vz=Math.max(25,(.5*185*t*t-this.ball.z)/t*arc+(1-arc)*36)}
serve(side:Side){const p=this.a[side],q=cl(1-Math.abs(this.ball.z-48)/34,0,1),right=this.pointNo%2===0,ix=side?0:((keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0));let tx=(right?-38:38)*(side?-1:1)+ix*18+(Math.random()-.5)*(1-q)*55,ty=(side?1:-1)*67;this.launch(tx,ty,cl(.7-p.p.s[2]!*.016-q*.08,.43,.72),1);this.last=side;this.live=this.serveLive=true;p.hit=true}
fault(){if(this.attempt===1){this.attempt=2;this.toss=this.live=this.serveLive=false;const p=this.a[this.server];this.ball={x:p.x,y:p.y,z:12,vx:0,vy:0,vz:0};this.delay=.45;this.msg='SECOND SERVE'}else{this.msg='DOUBLE FAULT';this.point(this.server?0:1)}}
point(w:Side){this.live=this.serveLive=this.toss=false;this.pts[w]++;const o=w?0:1;if(this.pts[w]>=4&&this.pts[w]-this.pts[o]>=2){this.games[w]++;this.pts=[0,0];if(this.games[w]>=3&&this.games[w]-this.games[o]>=2){this.done=w;this.msg=w?'CPU WINS':'YOU WIN';return}this.server=this.server?0:1}this.pointNo++;this.reset()}
score(i:number){const a=this.pts[i]!,b=this.pts[i?0:1]!;if(a>=3&&b>=3)return a>b?'AD':'40';return ['0','15','30','40'][a]||'40'}
hit(side:Side){const p=this.a[side],rel=this.ball.x-p.x,bh=side?rel>0:rel<0,stat=p.p.s[bh?1:0]!,smash=this.ball.z>30;let tx,ty;if(!side){const x=(keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0),y=(keys.has('ArrowDown')?1:0)-(keys.has('ArrowUp')?1:0);tx=x?x*69:-this.a[1].x*.65;ty=y<0?-157:y>0?-72:-126}else{tx=(this.a[0].x>0?-1:1)*(57+p.p.s[5]!*1.5)+(Math.random()-.5)*12;ty=Math.random()<.08?72:128+(Math.random()-.5)*36}tx+=(Math.random()-.5)*(11-stat)*2.2;const dist=Math.hypot(tx-this.ball.x,ty-this.ball.y),t=cl(dist/(260+stat*12+(smash?72:0)),smash?.36:.48,smash?.58:.93);this.launch(tx,ty,t,smash?.7:.92);this.last=side;this.bounces=0;p.hit=true;this.msg=smash?'SMASH':bh?'BACKHAND':'FOREHAND'}
contact(side:Side){const p=this.a[side];if(!p.sw||p.hit)return;const e=.34-p.sw;if(e<.075||e>.235)return;const d=Math.hypot(this.ball.x-p.x,this.ball.y-p.y);if(d>22+p.p.s[3]!*1.2||this.ball.z<1||this.ball.z>30+p.p.s[5]!*2.2)return;if((side===0&&this.ball.vy>20)||(side===1&&this.ball.vy<-20))return;this.hit(side)}
update(dt:number){if(this.done)return;this.a.forEach(p=>p.update(dt));if(this.delay>0){this.delay-=dt;return}const s=this.a[this.server];if(!this.live){if(!this.toss){if(!this.server&&take('Space')||this.server){this.toss=true;this.ball={x:s.x,y:s.y,z:14,vx:0,vy:this.server?7:-7,vz:82}}}else{if(!this.server&&take('Space')&&this.ball.z>24&&this.ball.z<62){s.swing();this.serve(0)}if(this.server&&this.ball.z>43&&this.ball.vz<20){s.swing();this.serve(1)}this.ball.x+=this.ball.vx*dt;this.ball.y+=this.ball.vy*dt;this.ball.z+=this.ball.vz*dt;this.ball.vz-=185*dt;if(this.ball.z<=0&&!this.live)this.fault()}return}
const u=this.a[0],dx=(keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0),dy=(keys.has('ArrowDown')?1:0)-(keys.has('ArrowUp')?1:0);if(dx||dy)u.move(dx,dy,dt);if(take('Space'))u.swing();const cpu=this.a[1],land=this.land(),tx=this.last===0?cl(land.x,-90,90):0,ty=this.last===0?cl(land.y+30,-145,-70):-126;if(Math.hypot(tx-cpu.x,ty-cpu.y)>3)cpu.move(tx-cpu.x,ty-cpu.y,dt);if(this.last===0&&this.ball.y<-20&&this.ball.vy<0&&Math.hypot(this.ball.x-cpu.x,this.ball.y-cpu.y)<38+cpu.p.s[5]!*1.7&&this.ball.z<42)cpu.swing();this.stepBall(dt);this.contact(0);this.contact(1)}
land(){const a=-92.5,b=this.ball.vz,c=this.ball.z,d=Math.max(0,b*b-4*a*c),rs=[(-b+Math.sqrt(d))/(2*a),(-b-Math.sqrt(d))/(2*a)].filter(v=>v>0),t=Math.max(...rs,.2);return{x:this.ball.x+this.ball.vx*t,y:this.ball.y+this.ball.vy*t}}
stepBall(dt:number){const py=this.ball.y,pz=this.ball.z;this.ball.x+=this.ball.vx*dt;this.ball.y+=this.ball.vy*dt;this.ball.z+=this.ball.vz*dt;this.ball.vz-=185*dt;if((py<0)!=(this.ball.y<0)){const t=Math.abs(py)/(Math.abs(py)+Math.abs(this.ball.y)),z=pz+(this.ball.z-pz)*t;if(z<18){this.msg='NET';this.point(this.last?0:1);return}}if(this.ball.z<=0&&this.ball.vz<0){this.ball.z=0;this.ball.vz=Math.abs(this.ball.vz)*.56;this.bounces++;if(this.serveLive){const right=this.pointNo%2===0,sign=this.server?1:-1,ok=Math.sign(this.ball.y)===sign&&Math.abs(this.ball.y)<=100&&Math.abs(this.ball.x)<=82&&(this.server?(right?this.ball.x>=0:this.ball.x<=0):(right?this.ball.x<=0:this.ball.x>=0));if(!ok){this.fault();return}this.serveLive=false}else if(Math.abs(this.ball.x)>82||Math.abs(this.ball.y)>178){this.msg='OUT';this.point(this.last?0:1)}else if(this.bounces>=2)this.point(this.last)}}
draw(){court();panel(14,14,188,68);X.fillStyle='#eef3e4';txt(this.a[0].p.name,26,34,13,'left');txt(this.a[1].p.name,26,61,13,'left');X.fillStyle='#dbe66f';txt(String(this.games[0]),135,34,15);txt(String(this.games[1]),135,61,15);X.fillStyle='#eef3e4';txt(this.score(0),177,34,13);txt(this.score(1),177,61,13);this.a[1].draw();const sh=proj(this.ball.x,this.ball.y),p=proj(this.ball.x,this.ball.y,this.ball.z);X.fillStyle='rgba(0,0,0,.28)';X.beginPath();X.ellipse(sh.x,sh.y+2,4*sh.s,2*sh.s,0,0,7);X.fill();X.fillStyle='#e7ee6f';X.beginPath();X.arc(p.x,p.y,Math.max(2.3,3.2*p.s),0,7);X.fill();this.a[0].draw();if(this.msg){panel(195,278,210,42);X.fillStyle='#f0f5dc';txt(this.msg,300,300,16)}}}
class App{screen='menu';menu=0;sel=0;m:Match|null=null;br:P[]=[];round=0;user:P|null=null;
update(dt:number){if(this.screen==='menu'){if(take('ArrowUp')||take('ArrowDown'))this.menu=1-this.menu;if(take('Space')||take('Enter'))this.screen='select'}else if(this.screen==='select'){if(take('ArrowLeft'))this.sel=(this.sel+15)%16;if(take('ArrowRight'))this.sel=(this.sel+1)%16;if(take('ArrowUp'))this.sel=(this.sel+12)%16;if(take('ArrowDown'))this.sel=(this.sel+4)%16;if(take('Escape'))this.screen='menu';if(take('Space')||take('Enter')){this.user=ps[this.sel]!;if(this.menu===0){this.br=[this.user,...ps.filter(p=>p!==this.user).sort(()=>Math.random()-.5)];this.round=0;this.screen='bracket'}else{const q=ps.filter(p=>p!==this.user);this.m=new Match(this.user,q[Math.floor(Math.random()*q.length)]!);this.screen='match'}}}else if(this.screen==='bracket'){if(take('Space')||take('Enter')){const i=this.br.indexOf(this.user!),o=i%2?i-1:i+1;this.m=new Match(this.user!,this.br[o]!);this.screen='match'}}else if(this.screen==='match'){this.m!.update(dt);if(this.m!.done!==null&&(take('Space')||take('Enter'))){if(this.m!.done===1||this.menu===1){this.screen='menu';this.m=null;return}const n:P[]=[];for(let i=0;i<this.br.length;i+=2){const a=this.br[i]!,b=this.br[i+1]!;n.push(a===this.user||b===this.user?this.user!:(a.s.reduce((x,y)=>x+y)>b.s.reduce((x,y)=>x+y)?a:b))}this.br=n;this.round++;this.m=null;this.screen=n.length===1?'champ':'bracket'}}else if(this.screen==='champ'&&(take('Space')||take('Enter')))this.screen='menu'}
draw(){if(this.screen==='match'){this.m!.draw();if(this.m!.done!==null){panel(120,215,360,170);X.fillStyle=this.m!.done?'#f0d0b7':'#e8ee6f';txt(this.m!.done?'MATCH LOST':'YOU WIN',300,262,30);X.fillStyle='#edf4e6';txt(`${this.m!.games[0]} – ${this.m!.games[1]}`,300,308,24);X.fillStyle='#93a79b';txt('SPACE TO CONTINUE',300,356,12)}return}X.fillStyle='#18271f';X.fillRect(0,0,600,600);if(this.screen==='menu'){panel(90,86,420,430);X.fillStyle='#eff4df';txt('TENNIS',300,146,46);X.fillStyle='#dbe66f';txt('CHAMPIONSHIPS',300,194,27);['TOURNAMENT','EXHIBITION'].forEach((v,i)=>{X.fillStyle=i===this.menu?'#e8ee6f':'#dbe5d8';txt(`${i===this.menu?'› ':''}${v}`,300,324+i*62,20)});X.fillStyle='#7f9488';txt('ARROWS + SPACE',300,454,13)}else if(this.screen==='select'){X.fillStyle='#edf4e6';txt('SELECT PLAYER',300,42,25);ps.forEach((p,i)=>{const x=26+i%4*142,y=78+Math.floor(i/4)*90;X.fillStyle=i===this.sel?'rgba(219,230,111,.17)':'rgba(255,255,255,.035)';X.fillRect(x,y,126,72);X.strokeStyle=i===this.sel?'#dbe66f':'#46574c';X.strokeRect(x+.5,y+.5,125,71);X.fillStyle='#e7ede3';txt(p.name,x+63,y+24,12);X.fillStyle='#899b90';txt(`OVR ${p.s.reduce((a,b)=>a+b)}`,x+63,y+50,11)})}else if(this.screen==='bracket'){X.fillStyle='#edf4e6';txt(['ROUND OF 16','QUARTERFINAL','SEMIFINAL','FINAL'][this.round]||'FINAL',300,44,24);const pairs=this.br.length/2,g=Math.min(82,350/pairs);for(let i=0;i<pairs;i++){const a=this.br[i*2]!,b=this.br[i*2+1]!,y=105+i*g;X.fillStyle=a===this.user||b===this.user?'rgba(219,230,111,.13)':'rgba(255,255,255,.035)';X.fillRect(72,y,456,56);X.fillStyle=a===this.user?'#e8ee6f':'#d5ded4';txt(a.name,98,y+18,12,'left');X.fillStyle=b===this.user?'#e8ee6f':'#d5ded4';txt(b.name,98,y+40,12,'left');X.fillStyle='#687f71';txt('VS',488,y+29,11)}X.fillStyle='#9aac9f';txt('SPACE TO PLAY',300,555,12)}else{panel(92,112,416,376);X.fillStyle='#e8ee6f';txt('CHAMPION',300,190,44);X.fillStyle='#edf4e6';txt(this.user?.name||'YOU',300,251,24);txt('★',300,326,50);X.fillStyle='#91a598';txt('SPACE TO RETURN',300,430,11)}}}
const app=new App();let prev=performance.now();function frame(t:number){const dt=Math.min(.033,(t-prev)/1000);prev=t;app.update(dt);app.draw();pressed.clear();requestAnimationFrame(frame)}requestAnimationFrame(frame);
